### ISSUE TITLE
Cocoapods update 'ARSlidingPanel' still pulling in 0.1.0

### ISSUE THREAD

**Issue by phoumano** [andriirogulin/ARSlidingPanel#11]
I'm trying to update this library and updating it via Cocoapods is still seeing 0.1.0 as the latest release.

**Comment by orenk86** [comment]
@andriirogulin Please add a tag `0.1.1` to this repo, and push the updated podspec to the Cocoapods specs repo. The Cocoapods repo is still showing version `0.1.0`...

**Comment by andriirogulin** [comment]
Done :)
