### ISSUE TITLE
How to set a max expanded height for panel?

### ISSUE THREAD

**Issue by mielet** [andriirogulin/ARSlidingPanel#2]
How would I go about setting the maximum height for the panel in its expanded state, currently the default is full screen and I would like to shrink it, thanks

**Comment by orenk86** [comment]
Hi @mielet ,
I also needed this feature, so I forked this repository and added it myself.
There's a property called maxPanelHeight which defines the panel's max height when maximized.
But I have a little bug with landscape mode for now. Portrait works fine.

Check it out if you want:
https://github.com/orenk86/ARSlidingPanel

**Comment by mielet** [comment]
Thank you very much! I was trying to accomplish this myself but I have very little C knowledge. Is it intended that the panel be able to expand past its max height by being dragged with your changes?

**Comment by orenk86** [comment]
You can drag it past your pre-defined maximum height, yes. But it'll go back to the maximum height as soon as you lift your finger.
You can, of course, change the maximum height to whatever you want at run time if you want.
